### ISSUE TITLE
Does the clip fit the IR sensor in #38?

### ISSUE THREAD

**Issue by JRDevo** [golles/ha-kamstrup_403#101]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Just curious, when I look at the shape of the device in in ticket #38 then the clip provided in the readme, eg

https://www.aliexpress.com/item/1005003509520122.html
https://www.thingiverse.com/thing:5615493

The sensor looks like it isn't the same shape. Does it fit in the clip?
Also wondering how do people attach the sensor without a clip? Tape? Are there alternatives?

Appreciate any guidance!

**Comment by golles** [comment]
Probably better to ask your question in #38
It's not very likely anyone will see this question here
