### ISSUE TITLE
Support for SERVICE HOMEASSISTANT.UPDATE_ENTITY and disable standard polling interval.

### ISSUE THREAD

**Issue by jorgh6** [golles/ha-kamstrup_403#117]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Since most Kamstrup heat meters are battery powered, we should limit the number of times the integration reads the data from the meter. Now, the interval is configurable to a single interval, which starts when the integration starts, and thus is kind of random.

If the integration would support the homeassistant.update_entity service, we could configure specific polling times and intervals through automations or node red. This would for instant allow polling at the 59th minute of every hour, so the statistics in the energy dashboard more accurately match the energy consumption of the hours covered in the graph. In addition, it would allow different polling intervals during day/night etc.

**Comment by golles** [comment]
Hi, I see what you want to achieve. Something like this isn't supported at the moment, my suggestion is to set the interval to `86400` seconds (once a day, max value) and use indeed the service to manually update in an automation on the preferred time:

```yaml
service: homeassistant.update_entity
target:
  entity_id: sensor.kamstrup_403_heat_energy_e1
```

This will result in 25 readings per day, which should be fine for the battery.

**Comment by jorgh6** [comment]
Thanks for the quick reply.

I did not know what the maximum interval was, so that is good to know.

The feature request was to add a toggle to the config to disable the interval and trigger 'external' updates. I've seen this in other integrations as well.

Never the less, this solution works.

Maybe on some rainy sunday morning when you've got nothing else to do, it's a nice little feature update ;-)

Regards,

Jorg
