### ISSUE TITLE
Home Assistant crashes when changing scaninterval

### ISSUE THREAD

**Issue by scoop643** [golles/ha-kamstrup_403#122]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

When i try to change the scaninterval time from 1800 to another value (example 1790), Home Assistant crashes and is goging in a reboot. Approx 10 - 15 minutes later, Home Assistant is online again with a 1800 seconds of scaninterval.

I want to change the time to 86400.

Does anybody know what I am doing wrong?

### Integration version

2.6.2

### Home Assistant version

2024.6.4

### Python version

3.12.2

**Comment by golles** [comment]
Reloading the integration manually doesn't cause the reload loop

**Comment by golles** [comment]
I've got a PR that seems to fix the issue.
I didn't have much time to investigate the problem so I'm a bit hesitant to merge it until I understand the problem better. If you really need to have the fix ASAP, feel free to check out the PR branch or apply the change locally.

**Comment by scoop643** [comment]
I changed the file __init__.py manually and it works. Thank you!

**Comment by golles** [comment]
> I changed the file **init**.py manually and it works. Thank you!

Keep me posted, I'm also running this locally now
