### ISSUE TITLE
Value GJ is facor 1000 to high

### ISSUE THREAD

**Issue by koningpeter** [golles/ha-kamstrup_403#126]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

I have a small problem. I can't seem to figure out how to get the m3 and GJ values correct. It says for example 261.730 m3 instead of 261,730m3. Is there a way to adjust this?

### Integration version

2.6.2

### Home Assistant version

core-2024.9.3

### Python version

 3.12.4

**Comment by golles** [comment]
Can you explain where it shows that? For example on your dashboard, in the integration settings, or the developer tools (states)?

For the last one, you can view it in its raw value. On a dashboard, and in integrations, it is displayed according to your Home Assistant configuration which you can change in your profile settings (number format).

**Comment by koningpeter** [comment]
Hi Sander,

Here are some screenshot from the dashboard where it shows. The meter bij Gas shows 0m3, the Gas consumption shows some usage in 0,02m3 and the heat sensor in the individual devices shows 10.82 kWh.

In the integrations setting I see the same value for both sensors as mentioned.

￼￼￼

￼

Best regards,


Peter van Voorst

**Comment by koningpeter** [comment]
I have changed the number format, it now looks like this:

￼

Met vriendelijke groet,


Peter van Voorst

**Comment by golles** [comment]
Your images didn't upload

**Comment by koningpeter** [comment]
I'm sorry, here are the screesnhots.

![Scherm­afbeelding 2024-10-02 om 16 00 29](https://github.com/user-attachments/assets/6b08eb6f-fbe7-436d-8d60-64b04bbbd25f)
I
![Scherm­afbeelding 2024-10-02 om 16 05 07](https://github.com/user-attachments/assets/7ba098b9-3889-4063-b9d8-6966257a6795)
![Scherm­afbeelding 2024-10-02 om 16 07 06](https://github.com/user-attachments/assets/78c144d3-38a9-4fa4-acfa-73a3507fc374)

![Scherm­afbeelding 2024-10-02 om 16 00 11](https://github.com/user-attachments/assets/00e71711-06a2-48b1-b1b8-c5f3a14adc64)
![Scherm­afbeelding 2024-10-02 om 16 00 22](https://github.com/user-attachments/assets/f8adb1f3-b6da-4d3f-97cd-5a529b015997)

**Comment by koningpeter** [comment]
Today I took some new screenshots with the numeber format corrected. And as you can see the value in the individual devices list is overstated (7,28 kWh) and the value in the Gas section is around 0,03 m3. Though the values of the sensors in the kammstrup section both show the right total value 261,91 GJ.

<img width="1440" alt="Scherm­afbeelding 2024-10-03 om 13 21 02" src="https://github.com/user-attachments/assets/945e0b52-0a20-4cfa-bb8a-eaf6c7ae0a77">
<img width="1440" alt="Scherm­afbeelding 2024-10-03 om 13 21 08" src="https://github.com/user-attachments/assets/4e4000eb-2dde-4494-a706-1ba86abac0bf">
<img width="1440" alt="Scherm­afbeelding 2024-10-03 om 13 21 17" src="https://github.com/user-attachments/assets/19978ed7-a847-4b70-8ca7-15ed6e9f9347">
<img width="1440" alt="Scherm­afbeelding 2024-10-03 om 13 22 28" src="https://github.com/user-attachments/assets/26bb39f9-22a3-42f9-b345-13e4bae4b957">

**Comment by golles** [comment]
Please keep in mind that the 3 things you are comparing are using different units.
On the integrations page, you see GJ for the meter usage, and M3 for gas usage (1).
In the gas consumption graph, gas is shown as M3 as well (2)
In the individual devices total usage your heat energy is shown as kWh (3). This is how HA decided to implement it. This is why I haven't added the meter there, as to me it doesn't make a lot of sense and it will make it harder to see the difference between the other sensors being tracked.

The integration page shows the current meter readings and the energy dashboard shows the usage for the given period (which you can set in the top right), in your case today.
