### ISSUE TITLE
Socket UART not reconnecting

### ISSUE THREAD

**Issue by mickkn** [golles/ha-kamstrup_403#127]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

Hi, I have been working on a [solution](https://github.com/mickkn/ESP8266SerialBridge) for a Wifi Serial Bridge, to connect this integration to a ESP8266, and it seems to work, but the Integration is not reconnecting when the ESP has been offline and gets back online.

Is that right or am I doing something wrong ?

I guess there should be a re-init when using a socket connection to uart and errors happen (or just no data is fetched). 

This is just an example, where the Socket is set to poll every 10s and the ESP is restarted - it is not connected to my meter at this point.

```2024-10-14 18:50:35.129 ERROR (MainThread) [custom_components.kamstrup_403] Finished update, No readings from the meter. Please check the IR connection
2024-10-14 18:50:48.354 ERROR (MainThread) [custom_components.kamstrup_403] Finished update, No readings from the meter. Please check the IR connection
2024-10-14 18:50:59.502 ERROR (MainThread) [custom_components.kamstrup_403] Finished update, No readings from the meter. Please check the IR connection
2024-10-14 18:51:09.512 ERROR (MainThread) [custom_components.kamstrup_403] Error fetching kamstrup_403 data: 
```

### Integration version

2.6.3

### Home Assistant version

2024.8.2

### Python version

3.12

**Comment by golles** [comment]
That's a cool idea!
I would suggest enabling debug logging for this component to get more info out of it. The third line from your log is caused by home assistant. The first 2 lines are correct if you haven't connected it to an actual meter.

**Comment by mickkn** [comment]
> That's a cool idea! I would suggest enabling debug logging for this component to get more info out of it. The third line from your log is caused by home assistant. The first 2 lines are correct if you haven't connected it to an actual meter.

Yeah, I haven't got my RS232 IR eye yet, but the messages are coming through. Did something similar with a Rpi and a USB IR Eye in the past, but also had a problem when connection was lost if the TCP socket had disconnected.

**Comment by mickkn** [comment]
It might not be the best approach, but if I raise ConfigEntryNotReady() when there is no readings in coordinator.py it re-init the integration, and reconnect to the TCP socket. But are there a better way to make a reconnection ?

```        
if failed_counter == len(self._commands):
    _LOGGER.error("Finished update, No readings from the meter. Please check the IR connection")
    raise ConfigEntryNotReady() from Exception
`

**Comment by golles** [comment]
Have you already connected it with an IR reader to a meter?
Have you been able to set up the integration or are you stuck in configuring it?
Have you configured a lower scan interval for your testing? By default, it will only attempt to read from the meter once per hour. At each read attempt it will make sure to open the connection.
If raising `ConfigEntryNotReady` in `_async_update_data` attempts to reconnect, then this can be a problem as this can cause many readings to the meter which drains the internal battery. This exception is meant for the setup of the integration

**Comment by mickkn** [comment]
Let me try to explain it a little better.

- I've my ESP8266 connected to the WiFi and a RS232 FTDI adapter connected to it, to see the output (acting as the IR eye, without replying)
- Then I've configured the integration to transmit every 10s for testing purpose 3600 is default as you mentioned.
- The integration is configured to connect to socket://myip:8880 which is the UART0 on the ESP8266
- When the integration is started I continuously see the start message every 10s
- 80 3f 10 1b f9 20 3c 20 44 20 63 20 71 03 e9 03 ec 1a aa
- 80 3f 10 1b f9 20 3c 20 44 20 63 20 71 03 e9 03 ec 1a aa
- Then I just resets the ESP8266 and let it reconnect to the Wi-Fi
- And I expected the integration to kind a reconnect to the socket, but it never happens, only when I re-init the integration
- I then tried to change some of the code to force a ConfigEntryNotReady(), but it only get me to a reconnect, I can see in the debug terminal for the ESP8266 that it connects again, but the start message is not transmitted though, so it might not be THE solution. It also kinda seems like a bad hack to just force a re-init :)
