### ISSUE TITLE
sensor.kamstrup_403_tempdiff untit of measurement switched (K / C)?

### ISSUE THREAD

**Issue by Gera1850** [golles/ha-kamstrup_403#129]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

Hi, 
When I use sensor.kamstrup_403_tempdiff in an entity card the numeric value is in Celcius but the unit of measurement is Kelvin. When I change it to Celsius the numeric value in de entity card is in Kelvin and the unit of measurement in Celsius.

Am I overlooking something?

### Integration version

2.6.3

### Home Assistant version

core-2024.10.4

### Python version

3.12.4

**Comment by golles** [comment]
The meter exposes this value in K. To be honest I had to check ChatGPT for this as well.

> Absolute Temperatures vs. Temperature Differences
> 
> Absolute Temperature:
> When we say a temperature is “1.7°C” or “1.7K,” we mean an actual point on the temperature scale.
> In absolute terms, 1.7°C is not the same as 1.7K because they’re based on different starting points (0°C = 273.15K).
> If you convert 1.7°C to Kelvin, you would get 1.7°C = 274.85K.
> 
> Temperature Difference:
> When we calculate a difference between two temperatures, 1°C is the same as 1K in terms of magnitude.
> So, a temperature difference of 1.7°C can also be expressed as 1.7K, as they represent the same interval between two points.
>
> In example:
> 10°C and 8.3°C have a difference of 1.7°C, which can also be expressed as 1.7K because we’re only talking about the gap between them, not their absolute temperatures.

When you let Home Assistant convert this value, it considers it as an absolute temperature and there it would go wrong.

You can customize the unit in yaml in your config:
```yaml
homeassistant:
  customize:
    sensor.kamstrup_403_tempdiff:
      unit_of_measurement: °C
```

**Comment by Gera1850** [comment]
Thanks for the explanation. I didn't realize you were talking about the difference between the two values ​​and not the absolute value of the temperature. I'm going to customize my config.
