### ISSUE TITLE
Works with Kamstrup 603

### ISSUE THREAD

**Issue by johanneswseitz** [golles/ha-kamstrup_403#18]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

I just tried the plugin with the Kamstrup 603 recently installed in our flat. It works like a charm. All values are available and they seem correct. Thanks!

**Comment by golles** [comment]
Thanks, @johanneswseitz, also for the star :-)
I've updated the docs

**Comment by maikvitesse** [comment]
Can you maybe provide some more information about this @johanneswseitz ?
Would like to know which sensor you bought for example 😀
