### ISSUE TITLE
Request: Heat energy to M3 (for use in energy dashboard)

### ISSUE THREAD

**Issue by tmaniac** [golles/ha-kamstrup_403#22]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

First of all, thank you for your work!

Can you add a sensor to the integration that converts the heat energy (E1) to M3?
That way you can have the Gas equivalent for usage in the Energy dashboard.

according to the official government website [https://www.infomil.nl/onderwerpen/duurzaamheid-energie/energiebesparing/vragen-antwoorden/overige-vragen/omrekening-verbruik/](url)

1 GigaJoule = 31,6 m3

So, the formula should be  [x]GJ*31.6=m3

Thanks!

**Comment by golles** [comment]
Please have a look at issue #21. However, the formula provided there is slightly different...

**Comment by golles** [comment]
@tmaniac I requested this in the Month of "What the heck?!" forums
https://community.home-assistant.io/t/wth-allow-gj-gigajoule-as-a-long-term-statistic/469968

Feel free to add comments and your vote.

**Comment by golles** [comment]
Support for this is now done, see https://github.com/golles/ha-kamstrup_403/releases/tag/2.0.0
