### ISSUE TITLE
Error reading Temp2 Exception: bytearray index out of range

### ISSUE THREAD

**Issue by kalbfuss** [golles/ha-kamstrup_403#23]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

I have a Kamstrup 403 flow and heat meter connected to control unit for district heating, which I would like to integrate into Home Assistant.
I bought a [USB IR read/write module via Ebay](https://www.ebay.de/itm/274962288487). Installing the kamstrup component via HACS worked out of the box. I was able to connect to the USB IR read/write module and the meter is detected, however, no values are displayed. In the Home Assistant log I find two recurring error messages (see below).

### What version of this integration has the issue?

1.2.1

### What version of Home Assistant Core has the issue?

2022.9.0

### Home Assistant log

```shell
Error message 1:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/kamstrup_403/sensor.py:68
Integration: Kamstrup 403 (documentation, issues)
First occurred: 7:57:46 PM (3 occurrences)
Last logged: 7:59:46 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 386, in state
    native_unit_of_measurement = self.native_unit_of_measurement
  File "/config/custom_components/kamstrup_403/sensor.py", line 68, in native_unit_of_measurement
    return self.coordinator.data[self._command].get("unit")
KeyError: 87
```
Error message: 2
```
This error originated from a custom integration.

Logger: custom_components.kamstrup_403
Source: custom_components/kamstrup_403/__init__.py:100
Integration: Kamstrup 403 (documentation, issues)
First occurred: 7:57:46 PM (6 occurrences)
Last logged: 7:59:46 PM

Error reading Temp2 Exception: bytearray index out of range
Error reading Flow Exception: bytearray index out of range
```

### Additional information

This is my Kamstrup meter:

![1662661202095](https://user-images.githubusercontent.com/6892738/189196995-c49c7fd3-7c61-4589-8e00-85fd523f9c2d.jpg)

**Comment by golles** [comment]
Hi @kalbfuss 

I think this might be due to the reader not being perfectly placed on the meter. In my experience this positioning is pretty exact. 

Could you try moving the reader a bit and see after at least a minute of its able to read?

Also, can you post the logs from the logfile directly? In my experience the logs in the frontend do not always give all details, thanks.

**Comment by kalbfuss** [comment]
Thanks for your hint, @golles. It brought me onto the right track. I got it to work by
1. Inverting the IR sensor head
2. Inserting a piece of paper between the sensor head and the meter

Looking at the sensor head I noticed that it contains a transparent and a dark diode. Same is true for the sensor port on the kamstrup meter. Matching colors inversely required to turn the sensor head upside down.

The trick with the piece of paper I learnt from the following [thread](https://www.domoticz.com/forum/viewtopic.php?f=65&t=18116&start=20). It appears that the IR LED on some sensor heads is too bright and needs to be dampened.

I am very happy now. This is an awesome piece of software. Thank you so much for the great work.

**Comment by golles** [comment]
Thank you so much for explaining how you fixed this, I wasn't aware of such a thing.
I think I also have my reader upside down (cable goes up). Someone in my neighborhood 3d printed a holder to snap nicely onto the meter.

Maybe I should make a simple FAQ on the readme page with these tips.

Thank you so much for your kind words
