### ISSUE TITLE
Ser2Net support for network connected 

### ISSUE THREAD

**Issue by MuadDib007** [golles/ha-kamstrup_403#28]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

I would like to be able to read my Kamstrup meter with Home Assistant over the network.
The suggested reader is connected to an ESP8266 which makes a ser2net server available (Just like DSMR does, during setup you choose either serial or network connection)

Hopefully it is possible to add this feature to your code.

### Additional information

As shown by DSMR:
![image](https://user-images.githubusercontent.com/1944507/197499781-68b7c9f9-3681-4c70-8f13-eea8c64af3a8.png)
This is the step during setup where you are able to select network or serial
![image](https://user-images.githubusercontent.com/1944507/197499702-ca978b4f-b686-4f35-a8aa-482db259ab51.png)

**Comment by golles** [comment]
This is a nice idea, but I'm not planning to do this anytime soon.

If you're using an ESP8266, you can consider exposing the readings over mqtt or when you use ESPHome, the sensors will be directly added into HA.

**Comment by golles** [comment]
With the latest release, this component is able to connect to a remote serial connection, see https://github.com/golles/ha-kamstrup_403/releases/tag/2.5.0
