### ISSUE TITLE
Supporting Kamstrup 401

### ISSUE THREAD

**Issue by hepfister** [golles/ha-kamstrup_403#31]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

The Kamstrup 401 does not work with this plugin. Adding it would be highly appreciated.
I've found two projects on Github that might be helpful:
https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P071_Kamstrup401.ino
https://www.manualslib.com/manual/2117896/Kamstrup-Multical-401.html?page=52
https://github.com/siliconehuntsman/mc401

I can help testing the device. There are thousands of this model installed here in Arnhem. The potential user base ;-)

**Comment by golles** [comment]
Hi, as mentioned in the https://github.com/golles/ha-kamstrup_403#supported-devices section I'm not planning to support any other devices than the 403. All the meters that do work with the same protocol are just a nice-to-have.

**Comment by hepfister** [comment]
I read that but decided to ask anyway. I understand. Would love to fork it and develop my own. Not a programmer myself but never too old to learn right. Any suggestions where to start code wise would be great.

**Comment by golles** [comment]
In the current implementation, the sensors are defined in const.py https://github.com/golles/ha-kamstrup_403/blob/main/custom_components/kamstrup_403/const.py#L30-L320
And the protocol is defined in https://github.com/golles/ha-kamstrup_403/blob/main/custom_components/kamstrup_403/kamstrup.py
