### ISSUE TITLE
Kamstrup HA Energy cards

### ISSUE THREAD

**Issue by Wipnose** [golles/ha-kamstrup_403#32]
Hi Golles, 
Many thanks for the works done! Must confess that it did cost me several evenings for trying out the reading, but finally ;) ... the sensor is stably running with the use of a magnet (3cmx1cmx4mm) permanent on top of the meter and placing the IR detector with 1 cm distance from the eye. Once you push one of the buttons on the Kamstrup as start, then your integration keeps on working in HA and supplies the heat values and its attributes. Love it.

The next goal for me is to integrate the readings into HA energy cards. This requires two steps.
1. Would be really great when the ha-kamstrup_403 integration can also be configured with longterm statistics.  
Without extra configuration coding the HA Energy card is yet not able to list Kamstrup 403 Heat Energy (E1). When trying to select in the HA Energy dashboard card under the tab Gas Consumption" the longterm statistic entity of Kamstrup is not available. (And yes, I chose for this Gasstab, because this energy gastab has the same units i.e. GJ, as the Kamstrup has)    
The HA Energy card configuration states: "You’re configuring a statistic but you couldn’t find your source in the dropdown? That’s caused by a bug in the integration providing the entity. Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how." . 
Would you (Golles or other) be able to adjust the Kamstrup code such that the Heat Energy (E1) state_class is set to total_increasing that may resolve the 'bug'. (If I'm correctly interpreting https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics.)

2. I guess the other improvement step is that HA Dashboard Energy developer adjusts the title of the sub card 'Gas Consumption' into 'Gas or Heat Consumption'. That is all folks. 
Regards, Wipnose

**Comment by golles** [comment]
Will be part of #30

**Comment by golles** [comment]
#30 is done and released as version `2.0.0`, https://github.com/golles/ha-kamstrup_403/releases/tag/2.0.0
