### ISSUE TITLE
all entities, but HourCounter, are unavailable

### ISSUE THREAD

**Issue by TGgrimreaper** [golles/ha-kamstrup_403#33]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

I've installed kamstrup script but all data except HourCOunter stays at unavailable its been more then 24 hours. Most addons take a few min to load data? Its a first time install so not sure if it would have ever worked. If i use the kamstup software i can read all data, so the IR is fine to. Heat Energy is also not possible to select in the energy screen. Am i doing something wrong or???

Ive checked the path to the ir reader (Seems to be fine as hour counter is working). My home has a 603 kamstrup meter

### What version of this integration has the issue?

1.3

### What version of Home Assistant Core has the issue?

2022.11.1

**Comment by golles** [comment]
Is the hour counter increasing?

You could temporarily add the following to your config, to get more debug details:
```yaml
logger:
  default: warn
  logs:
    custom_components.kamstrup_403: debug
```

Often when no data is coming in, it usually means the IR head isn't placed correctly on the meter, this can be a very tedious job.

**Comment by TGgrimreaper** [comment]
Yes, the hour counter is increasing.  Where can i post this in the config?

**Comment by TGgrimreaper** [comment]
ive added a small piece of paper between the ir head and the kamstrup unit,. Its now working 👍

**Comment by IngmarVerheij** [comment]
Is there a way to manually trigger a read? I'm having a tough time getting the sensor (and keeping it) in position. Happy to run this in the terminal

**Comment by TGgrimreaper** [comment]
Ive taped it to the meter🤣

**Comment by TGgrimreaper** [comment]
Paper berween ir head and meter

**Comment by golles** [comment]
I'm using this btw: https://www.thingiverse.com/thing:5615493

**Comment by IngmarVerheij** [comment]
That really 3D printed object is really great to keep the sensor in place, without the ugly tape.
