### ISSUE TITLE
Cooling values

### ISSUE THREAD

**Issue by TGgrimreaper** [golles/ha-kamstrup_403#34]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Our cityheating has to option to cool. I only see data about heating. Is the cooling data also possible to add?

**Comment by TGgrimreaper** [comment]
Okay, how do i get key#? I assume the cooling has its own # or do i need tk read that data with kamstrup software to find it?

**Comment by golles** [comment]
According to 12.3 on this page: https://www.manualslib.com/manual/1595756/Kamstrup-Multical-403.html?page=114 your energy provider should be able to get this from Kamstrup
