### ISSUE TITLE
Does Multical 303 work also?

### ISSUE THREAD

**Issue by leandresz** [golles/ha-kamstrup_403#35]
### Meter

Kamstrup 303

### More info

Device 303 or 403 might be similar based on communication?

**Comment by golles** [comment]
You might try it out and let me know ;-)
I don't have a 303

**Comment by tarbax** [comment]
> ### Meter
> Kamstrup 303
> 
> ### More info
> Device 303 or 403 might be similar based on communication?

did you test it ?
