### ISSUE TITLE
Optical eye buying sharing thread

### ISSUE THREAD

**Issue by IngmarVerheij** [golles/ha-kamstrup_403#38]
### Meter

CP2102 USB 2.0 to OPTICAL INTERFACE IRDA Near Infrared IR Magnetic Adapter Transparent Transmission Communication Cable for Electricity Gas Water Meter Reading Data

### More info

Wanted to let you know that this sensor from AliExpress works and is easily to order (unlike the sensors I found on ebay.de).
https://www.aliexpress.com/item/1005003509520122.html?spm=a2g0o.order_list.0.0.8c821802V6UHMy

**Comment by golles** [comment]
Thanks for sharing.
I've recently removed a link to a reader from the `README.md` as I didn't feel like maintaining that

**Comment by HAEdwin** [comment]
I bought this one https://nl.aliexpress.com/item/1005004351799379.html

**Comment by PrutzerNL** [comment]
I can confirm that the north and south of the magnet does matter. If it is in the wrong direction you have to turn the magnet 180 degree. The place of the magnet has to be just above the screen.

Her a pictures and a new housing for the https://wiki.hal9k.dk/projects/kamstrup IR reader sensor:

https://www.thingiverse.com/thing:5179312

**Comment by JRDevo** [comment]
Just curious, when I look at the shape of the device in in ticket https://github.com/golles/ha-kamstrup_403/issues/38 then the clip provided in the readme, eg

https://www.aliexpress.com/item/1005003509520122.html
https://www.thingiverse.com/thing:5615493

The sensor looks like it isn't the same shape. Does it fit in the clip?
 If not, how did you attach yours?

Appreciate any guidance!

**Comment by HAEdwin** [comment]
In my case I did not attach the sensor (which is positioned at a slight angle). The sensor rests on two points so that it does not slip off.
![IMG_1109](https://github.com/golles/ha-kamstrup_403/assets/82239374/51b649e0-b263-4420-9c6e-fd30f5e0061f)
![IMG_1108](https://github.com/golles/ha-kamstrup_403/assets/82239374/9a25f140-a27e-4272-98c5-95f937a02b35)

**Comment by JRDevo** [comment]
@HAEdwin  Never noticed those little studs till now.

I think Ill grab a sensor try strap it on with velcro or rubber bands.

Thanks for the images and feedback!

**Comment by HoekRoel** [comment]
Im trying to get some readings from my kamstrup 603 but it won’t work. 

I made a small bracket which fits on the two small pins. 

![IMG_7793](https://github.com/golles/ha-kamstrup_403/assets/154553682/f8ee8998-d2d4-4acf-94a5-9f972c90f0cd)
![IMG_7791](https://github.com/golles/ha-kamstrup_403/assets/154553682/637f3e0f-013c-4d47-81d3-a547d766e5f7)
![IMG_7790](https://github.com/golles/ha-kamstrup_403/assets/154553682/0df66b6d-a95c-4763-9c08-335054af0092)

**Comment by PrutzerNL** [comment]
@HoekRoel: Don't you get any reading at all? Did you press the play buttun? You have to press it once to enable the IR leds.
Is the reader exactly above the IR leds?

**Comment by HAEdwin** [comment]
@HoekRoel Does the bracket cause the focal point between the IR-TX and RX LEDs to change? In other words, is the head now further away from the meter? Have you tried to just place the head without the bracket the way I did (picture earlier in this thread)? Did you set the correct serial parameters?

**Comment by HoekRoel** [comment]
@PrutzerNL & @HAEdwin 
no readings at all..  Pressed all the buttons i could find.. and as far as i know it is exactly above the IR Leds.. 

The bracket i made is only a ring which fits tight around te sensor but still keeps te sensor flat against the meter.  tried a lot of positions with the sensor..

With the serial parameters you mean de /dev/,...... ?

Will check the inside of the sensor next.. see if something is wrong there..

**Comment by HAEdwin** [comment]
> With the serial parameters you mean de /dev/,...... ?

Yes, but read page 74 "heartbeat and status indication" you might have to activate the IR-circuit. I'm not sure, not owning one but reading the manuals can help you out hopefully.

**Comment by TomNagel123** [comment]
page 74 of what document? I have the same problem with my Kamstrup 403 and the same Ali express optical eye. The usb port is configured, but no data. 
I pressed the buttons. With the camera of my phone I see no IR light coming from the optical eye by the way

**Comment by HoekRoel** [comment]
> page 74 of what document? I have the same problem with my Kamstrup 403 and the same Ali express optical eye. The usb port is configured, but no data. I pressed the buttons. With the camera of my phone I see no IR light coming from the optical eye by the way

I bought a new optical eye and after that it works fine. I

**Comment by Piepaa** [comment]
The IR sensor I used at the MC66 doesn't work on the 603.

@HoekRoel 
Which sensor did you use?

**Comment by HoekRoel** [comment]
> The IR sensor I used at the MC66 doesn't work on the 603.
> 
> @HoekRoel Which sensor did you use?

This one
https://a.aliexpress.com/_EuPQJap

**Comment by HAEdwin** [comment]
Er staat bij "In De Buurt Van" maar daarmee wordt bedoeld "near infrared". Ik heb ook een kop gekocht die near IR is.

**Comment by Piepaa** [comment]
Installed the new sensor, with the same result. Noreads from the Kamstrup 603.
@HoekRoel 
Did you changed anything specific in the golles software?

**Comment by HoekRoel** [comment]
> Installed the new sensor, with the same result. Noreads from the Kamstrup 603. @HoekRoel Did you changed anything specific in the golles software?

No. I didn’t change a thing. It just started working with the new sensor.

**Comment by HAEdwin** [comment]
Ask Johannes, he claims it should work with the 603 https://github.com/golles/ha-kamstrup_403/issues/18

**Comment by davidzki** [comment]
> > Installed the new sensor, with the same result. Noreads from the Kamstrup 603. [@HoekRoel](https://github.com/HoekRoel) Did you changed anything specific in the golles software?
> 
> No. I didn’t change a thing. It just started working with the new sensor.

Could you please provide a working link for the sensor if that’s possible? I also have a 603 and bought the following but I can’t get any readings:
https://www.aliexpress.com/item/1005002692498946.html

**Comment by davidzki** [comment]
> Ordered this: https://a.aliexpress.com/_EwGAtw8
> 
> Arrived after 5 days worked flawlessly. Also fits the printed mount.
> 
> ![Image](https://github.com/user-attachments/assets/404bfc01-8fe9-4bfd-8c6c-f409f3033776) ![Image](https://github.com/user-attachments/assets/547ebbf0-4177-40c3-ab32-44921d1be73d) ![Image](https://github.com/user-attachments/assets/d23e184d-74f7-4333-b436-dee892456d42) ![Image](https://github.com/user-attachments/assets/f224aba4-9f26-460e-86dc-bd9652e633d9)

Ordered the same one. Tried it on my 603. No readings at all unfortunately
