### ISSUE TITLE
Wireless IR reading

### ISSUE THREAD

**Issue by verrassing** [golles/ha-kamstrup_403#43]
My smart meter is placed in a rather inconvenient location. There is no ethernet connection in the vicinity. Therefore, it is not possible to connect my raspberry pi directly with a USB IR r/w cable. Is there any way to transmit the data wirelessly?

**Comment by golles** [comment]
To use this custom component I can only advice you to get a very long USB cable :-)

Alternatives you might look into:
https://gathering.tweakers.net/forum/list_messages/2097228
https://github.com/matthijsvisser/kamstrup-402-mqtt
