### ISSUE TITLE
Use HTTP request for fetching data from Kamstrup 401

### ISSUE THREAD

**Issue by Gilbertonl** [golles/ha-kamstrup_403#51]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

I now use a ESP8266 to get data from Kamstrup401. With a URL i can fetch data from the ESP8266. The IR reader is connected to the ESP8266
Example : `http://192.168.0.207/energy`
The response is: ` {"energy [GJ]" : 371.383,"power [kW]" : 0.0,"flow [l/h]" : 0,"water [m3]" : 27509.55,"tempin" : 29.48,"tempout" : 22.59,"tempdiff" : 6.89}`
So it would be nice if this also can be used.

**Comment by golles** [comment]
This is out of scope.

If you use an ESP to read the values from your meter, why not publish them to MQTT and let Home Assistant get them from there? Or when using ESPHome, you can publish the values directly into Home Assistant. In both these suggestions you can use push mechanisms instead of fetch, which is IMO always preferred.

**Comment by StevenLooman** [comment]
Or perhaps you can use the [rest](https://www.home-assistant.io/integrations/rest/) integration for this.

**Comment by vittrup88** [comment]
> ### Did you read the instructions?
> 
> 
> 
> - [X] I have read the [README](../blob/master/README.md).
> 
> 
> 
> ### The request
> 
> 
> 
> I now use a ESP8266 to get data from Kamstrup401. With a URL i can fetch data from the ESP8266. The IR reader is connected to the ESP8266
> 
> Example : `http://192.168.0.207/energy`
> 
> The response is: ` {"energy [GJ]" : 371.383,"power [kW]" : 0.0,"flow [l/h]" : 0,"water [m3]" : 27509.55,"tempin" : 29.48,"tempout" : 22.59,"tempdiff" : 6.89}`
> 
> So it would be nice if this also can be used.
> 
> 
> 
> ### Additional information
> 
> 
> 
> _No response_

Can you share the code for esp8266? I have multical 603 and would like esp to publish data into MQTT.

**Comment by Gilbertonl** [comment]
> > ### Did you read the instructions?
> > 
> > * [x]  I have read the [README](../blob/master/README.md).
> > 
> > ### The request
> > I now use a ESP8266 to get data from Kamstrup401. With a URL i can fetch data from the ESP8266. The IR reader is connected to the ESP8266
> > Example : `http://192.168.0.207/energy`
> > The response is: ` {"energy [GJ]" : 371.383,"power [kW]" : 0.0,"flow [l/h]" : 0,"water [m3]" : 27509.55,"tempin" : 29.48,"tempout" : 22.59,"tempdiff" : 6.89}`
> > So it would be nice if this also can be used.
> > ### Additional information
> > _No response_
> 
> Can you share the code for esp8266? I have multical 603 and would like esp to publish data into MQTT. Also the ir sensor is diy?

Sure, How can i contact you?

**Comment by vittrup88** [comment]
> 

Could you create a repo at your github and be could talk about it there? It might also be possible to do a direct esphome version for usage in home assistant like home assistant glow.

**Comment by vittrup88** [comment]
> > > ### Did you read the instructions?
> > > 
> > > * [x]   I have read the [README](../blob/master/README.md).
> > > 
> > > ### The request
> > > I now use a ESP8266 to get data from Kamstrup401. With a URL i can fetch data from the ESP8266. The IR reader is connected to the ESP8266
> > > Example : `http://192.168.0.207/energy`
> > > The response is: ` {"energy [GJ]" : 371.383,"power [kW]" : 0.0,"flow [l/h]" : 0,"water [m3]" : 27509.55,"tempin" : 29.48,"tempout" : 22.59,"tempdiff" : 6.89}`
> > > So it would be nice if this also can be used.
> > > ### Additional information
> > > _No response_
> > 
> > 
> > Can you share the code for esp8266? I have multical 603 and would like esp to publish data into MQTT. Also the ir sensor is diy?
> 
> Sure, How can i contact you?

Could you create a repo at your github and be could talk about it there? It might also be possible to do a direct esphome version for usage in home assistant like home assistant glow.

**Comment by cybrain29** [comment]
> > > ### Did you read the instructions?
> > > 
> > > * [x]   I have read the [README](../blob/master/README.md).
> > > 
> > > ### The request
> > > I now use a ESP8266 to get data from Kamstrup401. With a URL i can fetch data from the ESP8266. The IR reader is connected to the ESP8266
> > > Example : `http://192.168.0.207/energy`
> > > The response is: ` {"energy [GJ]" : 371.383,"power [kW]" : 0.0,"flow [l/h]" : 0,"water [m3]" : 27509.55,"tempin" : 29.48,"tempout" : 22.59,"tempdiff" : 6.89}`
> > > So it would be nice if this also can be used.
> > > ### Additional information
> > > _No response_
> > 
> > 
> > Can you share the code for esp8266? I have multical 603 and would like esp to publish data into MQTT. Also the ir sensor is diy?
> 
> Sure, How can i contact you?
Can you also share the ESP8266 code with me? I am in a similar situation where the meter is nowhere near the RPi. 

@vittrup88  Yes, the sensor is easy to make. I got a few PCBs from a user on tweakers.

**Comment by golles** [comment]
With the latest release, this component is able to connect to a remote serial connection, see https://github.com/golles/ha-kamstrup_403/releases/tag/2.5.0
