### ISSUE TITLE
Thanks for the kamstrup 403 HA Add-on

### ISSUE THREAD

**Issue by TheSimmayor** [golles/ha-kamstrup_403#53]
Hi Golles,

I started using HA and during the holidays installed your Kampstrup 403 add-on. It worked perfectly right out of the box. I used an IrDA from AliExpress that worked great even with a 5 meter USB extention cable. The first time i was lazy and used the short tty/USB1 notation in the configuration.  And sure enough, at the first reboot i lost the connection. 

Thanks for the thorough documentataion and the add-on!

**Comment by golles** [comment]
I appreciate your message, thanks!
