### ISSUE TITLE
Configure a specific time to scan the Kamstrup

### ISSUE THREAD

**Issue by TheSimmayor** [golles/ha-kamstrup_403#61]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

My Kamstrup403 is battery operated. The drain will be high when i scan every hour. In the long run daily values would be enough, at least for me. If the scan is performed everyday at 24:00 (12:00 midnight) it would have minimum drain on the battery and daily values are available. 

Is it possible to add a function, for instance in the configuration screen, to do a daily scan at 24:00?  

(I know that i can configure the scan interval with 86400 and wait until 24:00 to submit the configuration, but a daily scan feature would be user friendly)

**Comment by golles** [comment]
Hi @TheSimmayor,
I like your use case, but I won't be adding this to the component.
However, this is something you could very easily do with an automation, if you request an update of one of the entities, all the sensors of the component will be updated. I think this would help you implementing exactly what you want.
```yaml
service: homeassistant.update_entity
target:
  entity_id: sensor.kamstrup_403_heat_energy_e1

```
