### ISSUE TITLE
HA Integration and Kamstrup as separate modules

### ISSUE THREAD

**Issue by NeK000** [golles/ha-kamstrup_403#62]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

I am not a native Python developer but as looking into it to me it seems that there are two separate applications here.
One is the Home Assistant integration which shows the entities and the other one is the Kamstrup integration and logic for pulling up the sensor data.

Have you considered creating a different application from the core code that is the Kamstrup application and publish the response as a MQTT topics for Home Assistant or some other way ? Possible the Optical Eye with ESPHome or standalone raspberry ?

Why I am asking is because for me the heating system is located in the laundry room which is not a place where I would like to place the raspberry running Home Assistant :)

**Comment by golles** [comment]
> I am not a native Python developer but as looking into it to me it seems that there are two separate applications here. One is the Home Assistant integration which shows the entities and the other one is the Kamstrup integration and logic for pulling up the sensor data.

I've considered splitting the code into 2 python projects, but I'm not sure if I want to take ownership of pyKamstrup, there was a bit of chat about it in https://github.com/golles/ha-kamstrup_403/pull/56#issuecomment-1379523957

> Have you considered creating a different application from the core code that is the Kamstrup application and publish the response as a MQTT topics for Home Assistant or some other way ? Possible the Optical Eye with ESPHome or standalone raspberry ?

I'm not planning to do that, an MQTT or ESPHome solution should not require this custom component, as the data could be handled internally before exposing it to HA (via MQTT).
Please  have a look at #51 $43 #28 for some discussion about this subject.

**Comment by PauluzzNL** [comment]
For those that are looking for an MQTT-only solution, I recommend checking out the following project:
https://github.com/matthijsvisser/kamstrup-402-mqtt

I've by now found tons of project that use different versions of the pyKamstrup library which is a bummer, would be nice if libraries were using original source repositories as modules for example. 

I also don't have the time for it but if anyone is reading this, perhaps it's worth building an mqtt library on top of the pyKamstrup library that this project contains as some kind of submodule.

**Comment by golles** [comment]
With the latest release, this component is able to connect to a remote serial connection, see https://github.com/golles/ha-kamstrup_403/releases/tag/2.5.0
