### ISSUE TITLE
Kamstrup ESP8266 support

### ISSUE THREAD

**Issue by GGBMLC** [golles/ha-kamstrup_403#63]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Hi 
I am searching for a setup there can read data from my Kamstup 602 via the IR interface, by using standard HW like. D1 Mini ESP8266. 
Do you have any plansfor "transfer" the code to this platform? 
/Bo

### Additional information

.

**Comment by golles** [comment]
Nope, please have a look at other tickets, Please have a look at #62, #51 #43 #28 for some discussion about this subject.

**Comment by cybrain29** [comment]
@GGBMLC Even I am looking for a similar solution and stumbled upon these two resources. They look promising but I have not tested them. If it works for you, please let me know. I have a Kamstrup 601. 

- [https://github.com/ProudElm/ESPHome_multical_sensor](url)
- [https://github.com/cenobitedk/esphome_multical402](url)

**Comment by StevenLooman** [comment]
Perhaps it is an idea to include some notes regarding this in the `README`, @golles. These questions seem to pop up from time to time.

Also, @cybrain29, your links seem to point to a different URL (the issue tracker for this repo) than the text shows.

**Comment by cybrain29** [comment]
[https://github.com/ProudElm/ESPHome_multical_sensor](url)
[https://github.com/cenobitedk/esphome_multical402](url)
[https://github.com/sebbebebbe/Multical402MQTT](url)

@GGBMLC  updated links

**Comment by cybrain29** [comment]
[Multical402 MQTT](https://github.com/sebbebebbe/Multical402MQTT)
[ESPhome_Multical401](https://github.com/jeroen85/esphome_multical401)
[ESP Home Multical sensor](https://github.com/ProudElm/ESPHome_multical_sensor)
[ESPhome Multical 402](https://github.com/cenobitedk/esphome_multical402)

@GGBMLC updated links
