### ISSUE TITLE
Support for pulse over cable? 

### ISSUE THREAD

**Issue by danielholm** [golles/ha-kamstrup_403#64]
Hi,

Not a bug, rather a possibility of discussion. If wrong forum, please pass me a link on more info if possible.

I got this meter installed recently and our provider installed a cable directly into the meter, statingtthat it gives the same pulse output as the octo way. Great, I thought since it's free, not having to buy a complete, or parts for, and octo eye.

Now I am however unsure how to proceed. This integration states that I should have a USB device connected to the machine running Home assistant. What kind of USB device should that be in this case? I do have  a Pl2303 laying around. Could that be hooked up to the two cables in my meter?

Or should I take the esp path. In that case, how could I reuse the code from this integration?

Any help would be much appreciated.

**Comment by golles** [comment]
I wouldn't know. This integration will only work with a cable with an optical eye, for example, the one mentioned in #38
