### ISSUE TITLE
Entity names should be user-friendly

### ISSUE THREAD

**Issue by golles** [golles/ha-kamstrup_403#76]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

At the moment the entity names aren't very user-friendly.

Examples (draft):
HourCounter -> Hour counter
Temp1 -> Incoming temperature
Temp2 -> Outgoing temperature
MaxFlowDate_M -> Max flow date (month)
MaxFlowDate_Y -> Max flow date (year)

The best practise is to get the names from the manual, https://www.kamstrup.com/en-en/heat-solutions/meters-devices/meters/multical-403/documents

### Additional information

At the moment the entity id is computed from its name, a simple rename will result in a new entity making the old one unavailable.
A migration should be in place to deal with this for existing users, or the logic for name/id should be decoupled.

Another thing to take into consideration is translations (at least English en Dutch, others can be added by the community)

**Comment by HAEdwin** [comment]
This public source helps to specify the correct names: https://www.askom.pl/WebHelp/Asix_Evo_10/EN/Communication_Drivers_HTML5/index.htm#t=Kmp.htm
