### ISSUE TITLE
SSL Handshake error after installing integration

### ISSUE THREAD

**Issue by MiteZZ** [golles/ha-kamstrup_403#98]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md).

### The problem

I've installed the integration, and that worked. It recognized the reader, but no values where read ( maybe due to misplacement of the IR reader) 
But when I restart homeassistant, I'm not able to connect to it anymore. I'm getting a SSL handshake error. If I un-plug the USB of the reader out of the NUC 11(I'm running a Genergic x86-64 image) and power it, homeassistant works again. When I connect a monitor to it with the USB plugged in, I see that homeassistant starts up, but that's it, no connection possible. Also with different clients or external link.  

Is there something I've missed that I'm doing wrong? Any ideas? 
 

thanks! 

### Integration version

2.6.0

### Home Assistant version

core-2023.6.3

### Python version

3.11.4

### Home Assistant log

[home-assistant.log](https://github.com/golles/ha-kamstrup_403/files/11948625/home-assistant.log)

[home-assistant.log.1.txt](https://github.com/golles/ha-kamstrup_403/files/11948639/home-assistant.log.1.txt)

### Diagnostics

[diagnostics.py.txt](https://github.com/golles/ha-kamstrup_403/files/11948637/diagnostics.py.txt)

**Comment by golles** [comment]
Please attach the diagnostics file and also the home-assistant.log and or home-assistant.log.1 file

**Comment by MiteZZ** [comment]
I've added the files to the original post.

**Comment by golles** [comment]
> I've added the files to the original post. I needed to install the integration again and restart HA for the issue to come back.
> 
> I downloaded the logs after that with all the USB's unplugged.

Thanks, but I need the diagnostics file that you can get through Home Assistant, see https://www.home-assistant.io/integrations/diagnostics/

**Comment by golles** [comment]
There is no `SSL Handshake error` in your log files, so I guess that error came from another integration?

I see you configured the integration to use `/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0` but that doesn't seem to be available:
```
2023-07-04 12:54:52.519 ERROR (MainThread) [custom_components.kamstrup_403] Can't establish a connection to /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0
2023-07-04 12:54:52.520 WARNING (MainThread) [homeassistant.config_entries] Config entry '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0' for kamstrup_403 integration not ready yet: [Errno 2] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0'; Retrying in background
```

You've also seem to use the exact same device for DSMR and that can't be right.
```
2023-07-04 12:54:52.828 ERROR (MainThread) [homeassistant.components.dsmr] Error connecting to DSMR
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/dsmr/sensor.py", line 455, in connect_and_reconnect
    transport, protocol = await hass.loop.create_task(reader_factory())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/serial_asyncio/__init__.py", line 448, in create_serial_connection
    serial_instance = serial.serial_for_url(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB6AZ0PB-if00-port0'
```

So I think you need to sort out your serial devices

**Comment by MiteZZ** [comment]
Okay thanks I'll give that a try and see what happens. if that's not the solution I'll post the diagnostics file. 

Thank you much for your help so far!

**Comment by golles** [comment]
Did you manage to sort out the issue with your serial ports?

**Comment by MiteZZ** [comment]
Hi Golles, 

I think so, I've just had the time to try it. It seems that I'm not getting the error though. I did not get any values back from the Kamstrup but I'll try the allignment on the heatexchanger itself for that. 

Thanks anyway for you good help! I'll keep you posted.

**Comment by SanderGols-TomTom** [comment]
Keep me posted, also provide the diagnostic file and enable more logging https://github.com/golles/ha-kamstrup_403#collect-logs so we can see what's going on.

**Comment by MiteZZ** [comment]
Hi,

still no values sadly. 

Hereby my diagnostics file and the logs! 


[config_entry-kamstrup_403-76e5daa252fa6f72b6d19f4d8d646bba.json (1).txt](https://github.com/golles/ha-kamstrup_403/files/11980023/config_entry-kamstrup_403-76e5daa252fa6f72b6d19f4d8d646bba.json.1.txt)
[home-assistant.log](https://github.com/golles/ha-kamstrup_403/files/11980024/home-assistant.log)
[home-assistant.log.1.txt](https://github.com/golles/ha-kamstrup_403/files/11980025/home-assistant.log.1.txt)

**Comment by MiteZZ** [comment]
Hi all,  I'm now getting in the log: 

2023-07-17 14:32:01.420 DEBUG (MainThread) [custom_components.kamstrup_403] Start update
2023-07-17 14:32:01.420 DEBUG (MainThread) [custom_components.kamstrup_403] Get values for [60, 68, 99, 113, 1001, 1004]
2023-07-17 14:32:02.421 DEBUG (MainThread) [custom_components.kamstrup_403.pykamstrup] Rx Timeout
2023-07-17 14:32:02.421 DEBUG (MainThread) [custom_components.kamstrup_403] Finished update, 4 out of 0 readings failed
2023-07-17 14:32:02.421 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.001 seconds (success: True)

any ideas what the Rx timeout could fix? 

thanks!

**Comment by golles** [comment]
First of all, could you ensure the head is connected correctly to the meter, this is very tedious.
I guess the default timeout is too low for your setup, you should increase that to a higher number, eg. `2.0` see https://github.com/golles/ha-kamstrup_403#configuration

**Comment by MiteZZ** [comment]
> First of all, could you ensure the head is connected correctly to the meter, this is very tedious. I guess the default timeout is too low for your setup, you should increase that to a higher number, eg. `2.0` see https://github.com/golles/ha-kamstrup_403#configuration

Yes it is positioned correctly.  I didn't get any values so I went back with an raspberry pi setup that pushes the data via MQTT and that's working now. No clue why the integration doesn't work. 

Thanks for all your help though!
